version: '3.8'
services:
  db:
    image: postgres:16
    container_name: cinemax_db
    restart: always
    environment:
      POSTGRES_DB: cinemax
      POSTGRES_USER: cinemax_user
      POSTGRES_PASSWORD: cinemax_pass123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata:
